name: Build and Push notion Docker Image

on:
  workflow_dispatch:
    inputs:
      push:
        type: boolean
        description: Whether to push the image to the registry
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  build-chat-agent:
    name: Build and Push Chat Agent Docker Image
    uses: ./.github/workflows/build_and_push.yml
    with:
      image: notion-image
      context: stubs/notion
      dockerfile: stubs/notion/Dockerfile
      push: ${{ inputs.push || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
      build-args: |
        LIBS_IMAGE=750187922702.dkr.ecr.ap-south-1.amazonaws.com/lerndemo/learndemo-libs:${{ github.sha }}
      commit_sha: ${{ github.sha }}
    secrets: inherit
