name: Build and Push notion Docker Image

on:
  workflow_dispatch:
   inputs:
      image:
        description: Image name
        type: string
        required: true

      context:
        description: Docker build context directory
        type: string
        required: true

      dockerfile:
        description: Path to the Dockerfile
        type: string
        required: true

      commit_sha:
        description: Specific commit SHA to build from
        type: string
        required: true

      build-args:
        description: Build arguments to pass to the Dockerfile (new-line delimited string)
        type: string
        required: false
        default: ""

      skip-libs:
        description: Whether to skip installing libraries
        type: boolean
        required: false
        default: false

      push:
        description: Whether to push the image to registry
        type: boolean
        required: false
        default: false

      tag_list:
        description: Comma-separated list of tags to apply to the image
        type: string
        required: false
        default: ""

      arch:
        description: The architecture to build for (amd64 or arm64)
        type: string
        required: true

jobs:
  build-notion-agent:
    name: Build and Push notion Docker Image
    uses: ./.github/workflows/build_and_push.yml
    with:
      image: notion-image
      context: stubs/notion
      dockerfile: stubs/notion/Dockerfile
      commit_sha: ${{ inputs.commit_sha }}
      arch: amd64
